#!/bin/bash
echo 'Enter the question to go on the front of the card: '
read question 
echo 'Enter the answer to go on the back of the card: '
read answer
EXISTS=$(grep -i "$question | $answer" < flashcards.txt)
if [[  $EXISTS == "" ]]
then
    echo "$question | $answer" >> flashcards.txt
    echo "$question | $answer" >> again_flashcards.txt
else
    echo "Card already exists."
fi