#!/bin/bash

COURSE_DIR="$HOME/WANKI/$1"

echo '-=-=-=-=- CARD LIST -=-=-=-=-'
cat -n $COURSE_DIR/flashcards.txt | sort
echo ''
echo 'Select the card number(s) you would like to delete: '
read deletionNum 
echo ''
for word in $deletionNum
do
    cat -n $COURSE_DIR/flashcards.txt | sort | head -$word | tail -1
done

echo ''
echo 'Are you sure you would like to delete this selection? (y/n)'
while read confirmation
do
    if [[ $confirmation == "y" || $confirmation == "Y" ]]
    then
        for word in $deletionNum
        do
            CHECK=$(cat $COURSE_DIR/flashcards.txt | head -$word | tail -1)
            #cat flashcards.txt | grep -v "$CHECK"  # | tee flashcards.txt

            x=$(cat $COURSE_DIR/flashcards.txt) 
            echo "$x" | grep -v "$CHECK" > $COURSE_DIR/flashcards.txt

            x=$(cat $COURSE_DIR/easy_flashcards.txt) 
            echo "$x" | grep -v "$CHECK" > $COURSE_DIR/easy_flashcards.txt

            x=$(cat $COURSE_DIR/good_flashcards.txt) 
            echo "$x" | grep -v "$CHECK" > $COURSE_DIR/good_flashcards.txt

            x=$(cat $COURSE_DIR/hard_flashcards.txt) 
            echo "$x" | grep -v "$CHECK" > $COURSE_DIR/hard_flashcards.txt

            x=$(cat $COURSE_DIR/again_flashcards.txt) 
            echo "$x" | grep -v "$CHECK" > $COURSE_DIR/again_flashcards.txt

            
        done
        
        break
    elif [[ $confirmation == "n" || $confirmation == "N" ]]
    then
        echo "ok then I won't :(" 
        break
    else
        echo "Invalid input. Try again."
    fi
    echo 'Are you sure you would like to delete this card? (y/n)'
done
